steps:
  # STEP 0 - DJANGO CONTAINER
  - id: Build-container-django-demo
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker build -t gcr.io/$PROJECT_ID/django-app -f 'build/demo.Dockerfile' .

    # STEP 2 - PUSH DJANGO CONTAINER
    - id: Push-to-Container-Registry
      name: 'gcr.io/cloud-builders/docker'
      args:
        - push
        - gcr.io/$PROJECT_ID/django-app
      waitFor: [ "Build-container-django-demo" ]

