steps:
  # STEP 1 - CREATE DJANGO CONTAINER
  - id: Build-container-django-demo
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker build -t gcr.io/$PROJECT_ID/django-app -f 'build/demo.Dockerfile' .


  # STEP 2 - PUSH DJANGO CONTAINER
  - id: Push-to-Container-Registry
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/django-app
    waitFor: [ "Build-container-django-demo" ]


  # STEP 3 - CREATE GCS BUCKET
  - id: Create-bucket
    name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'mb', 'gs://$PROJECT_ID-tfstate']


  # STEPS 4 TO 6 - CREATE K8S CLUSTER
  # STEP 4 - TERRAFORM INIT
  - id: tf-init
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Infrastructure/
        terraform init
        

  # STEP 5 - TERRAFORM PLAN
  - id: tf-plan
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Infrastructure/
        terraform plan
        

  # STEP 6 - TERRAFORM APPLY
  - id: tf-apply
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Infrastructure/
        terraform apply -auto-approve
   

  # STEP 7 - CONNECT TO K8S CLUSTER
  - id: Connect-to-GKE
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
#     gcloud container clusters get-credentials django-app-cluster --region us-central1 --project playground-s-11-4a370ae9
    args:
      - container
      - clusters
      - get-credentials
      - django-app-cluster
      - --region=us-central1
      - --project=$PROJECT_ID
    waitFor: [ "tf-init-and-plan" ]


  # STEP 8 - DEPLOY DJANGO CONTAINER TO GKE
  - id: Deploy-to-GKE
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'kubectl'
    args:
      - apply
      - -f
      - k8s/django-deployment.yml


  # STEP 9 - DEPLOY DJANGO SERVICE TO GKE
  - id: Deploy-Service-to-GKE
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'kubectl'
    args:
      - apply
      - -f
      - k8s/django-service.yml