steps:
  # STEP 1 - CREATE DJANGO CONTAINER
  - id: Build-container-django-demo
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker build -t gcr.io/$PROJECT_ID/django-app -f 'build/demo.Dockerfile' .


  # STEP 2 - PUSH DJANGO CONTAINER
  - id: Push-to-Container-Registry
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/django-app
    waitFor: [ "Build-container-django-demo" ]


  # STEP 3 - CREATE GCS BUCKET
  - id: Create-bucket
    name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'mb', 'gs://$PROJECT_ID-tfstate']


  # STEP 4 - TERRAFORM INIT
  - id: tf-init
    name: 'hashicorp/terraform:0.12.24'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
  

  # STEP 4 - TERRAFORM PLAN
  - id: tf-plan
    name: 'hashicorp/terraform:0.12.24'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Infrastructure/
        terraform plan


#  # STEP 3 - CREATE CLUSTER USING TERRAFORM
#  - id: Create-cluster
#    name: 'hashicorp/terraform:0.12.24'
#    entrypoint: 'sh'
#    args:
#    - '-c'
#    - |
#      terraform init
#      terraform plan
#      terraform apply -auto-approve
#    waitFor: [ "Push-to-Container-Registry" ]
##    waitFor: [ "API-Container-registry", "API-Kubernetes-engine-api", "Push-to-Container-Registry" ]
